<?php foreach ($quests as $quest) : ?>
    <div class="quest-card card html-quest-body" id="quest<?= $quest['quest_id'] ?>" data-htmlid="quest<?= $quest['quest_id'] ?>" data-ddbid="<?= $quest['quest_id'] ?>" data-penid="pen<?= $quest['quest_id'] ?>" data-crossid="questcross<?= $quest['quest_id'] ?>" data-deletequestid="deletequestid<?= $quest['quest_id'] ?>" data-questnpcslot="questnpcslot<?= $quest['quest_id'] ?>" data-questinfo="quest-info-<?= $quest['quest_id'] ?>" data-updatequestinfo="update-quest-info-<?= $quest['quest_id'] ?>">
        <div>

            <div id="quest-info-<?= $quest['quest_id'] ?>">
                <h2><?= $quest['quest_name'] ?></h2>
                <div class="info">
                    <p>Quest Id: <?= $quest['quest_id'] ?></p>
                    <p>Quest Number: <?= $quest['quest_number'] ?></p>
                    <p>Money Reward: <?= $quest['money_reward'] ?></p>
                    <p>Experience Reward: <?= $quest['experience_reward'] ?></p>
                </div>
            </div>

            <div class="none" id="update-quest-info-<?= $quest['quest_id'] ?>">
                <form action="index.php?page=update-quest" method="POST">
                    <input type="hidden" name="quest-id" value="<?= $quest['quest_id'] ?>">
                    <div>
                        <label for="quest-name<?= $quest['quest_id'] ?>">Quest Title:</label>
                        <input type="text" name="quest-name" id="quest-name<?= $quest['quest_id'] ?>" value="<?= $quest['quest_name'] ?>">
                    </div>
                    <div>
                        <label for="quest-number<?= $quest['quest_id'] ?>">Quest Number:</label>
                        <input type="number" name="quest-number" id="quest-number<?= $quest['quest_id'] ?>" value="<?= $quest['quest_number'] ?>">
                    </div>
                    <div>
                        <label for="quest-money-reward<?= $quest['quest_id'] ?>">Money Reward:</label>
                        <input type="number" name="quest-money-reward" id="quest-money-reward<?= $quest['quest_id'] ?>" value="<?= $quest['money_reward'] ?>">
                    </div>
                    <div>
                        <label for="quest-experience-reward<?= $quest['quest_id'] ?>">Experience Reward:</label>
                        <input type="number" name="quest-experience-reward" id="quest-experience-reward<?= $quest['quest_id'] ?>" value="<?= $quest['experience_reward'] ?>">
                    </div>
                    <div>
                        <input type="submit" name="submit" value="Update quest">
                    </div>
                </form>
            </div>

        </div>

        <div class="quest-npc-slot" id="questnpcslot<?= $quest['quest_id'] ?>">
            <?php require 'views/_npc_inside_quest_cards.phtml' ?>
        </div>

        <div class="tools">
            <div class="edit-quest-pen edit-pen" id="pen<?= $quest['quest_id'] ?>">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
                </svg>
            </div>
            <div class="none close-edit-quest" id="questcross<?= $quest['quest_id'] ?>">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="black" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
            </div>
            <a class="delete-quest delete none" id="deletequestid<?= $quest['quest_id'] ?>" href="index.php?page=delete-quest&id=<?= $quest['quest_id'] ?>">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                </svg>
            </a>
        </div>

    </div>
<?php endforeach; ?>