<div id="dialogues-popup" class="none">
    <div class="tools delete" id="dialogue-popup-cross-icon">
        <svg class="delete" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
        </svg>
    </div>
    <div id="dialogue-popup-responce">
    </div>
</div>