<div class="dialogue-card">
    <p>I did not start your quest yet.</p>
</div>
<div class="dialogue-card">
    <img src="./public/uploads/NPC_img/<?= $dialogues['image'] ?>" alt="Photo of <?= $dialogues['name'] ?>">
    <p><?= $dialogues['before_quest'] ?></p>
</div>
<div class="dialogue-card">
    <p>I'm in the process of completing your quest.</p>
</div>
<div class="dialogue-card">
    <img src="./public/uploads/NPC_img/<?= $dialogues['image'] ?>" alt="Photo of <?= $dialogues['name'] ?>">
    <p><?= $dialogues['ongoing_quest'] ?></p>
</div>
<div class="dialogue-card">
    <p>I just completed your quest!</p>
</div>
<div class="dialogue-card">
    <img src="./public/uploads/NPC_img/<?= $dialogues['image'] ?>" alt="Photo of <?= $dialogues['name'] ?>">
    <p><?= $dialogues['complete_quest'] ?></p>
</div>
<div class="dialogue-card">
    <p>Anything else for me?</p>
</div>
<div class="dialogue-card">
    <img src="./public/uploads/NPC_img/<?= $dialogues['image'] ?>" alt="Photo of <?= $dialogues['name'] ?>">
    <p><?= $dialogues['after_quest'] ?></p>
</div>