<?php $noNpc = true;
foreach ($steps as $step) : ?>
    <?php if ($step['quest_id'] === $quest['quest_id'] && !empty($step['npc_id'])) : $noNpc = false; ?>
        <div class="npc-card">
            <input type="hidden" class="npc-quest-id" value="<?= $quest['quest_id'] ?>">
            <input type="hidden" class="npc-id-from-quest" value="<?= $step['npc_id'] ?>">
            <input type="hidden" class="npc-quest-step-number" value="<?= $step['step_number'] ?>">
            <img src="./public/uploads/NPC_img/<?= $step['npc_image'] ?>" alt="<?= $step['npc_name'] ?>'s photo">
            <div class="npc-infos under-text-1">
                <p>Order: <?= $step['step_number'] ?></p>
                <p>Name: <?= $step['npc_name'] ?></p>
                <p>Id: <?= $step['npc_id'] ?></p>
            </div>
            <div class="tools">
                <div class="remove-npc-from-quest delete none">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endforeach; ?>
<?php if ($noNpc) : ?>
    <div class="npc-card empty">
    </div>
<?php endif; ?>