<?php if (empty($quest['npcs'])) : ?>
    <div class="npc-card empty">
    </div>
<?php else : ?>
    <?php foreach ($quest['npcs'] as $step) : ?>

        <div class="npc-quest-card npc-card quest<?= $quest['quest_id'] ?>" id="npcid<?= $step['npc_id'] ?>" data-npcddbid="<?= $step['npc_id'] ?>" data-npchtmlid="npcid<?= $step['npc_id'] ?>" data-npcstep="<?= $step['step_number'] ?>" data-npcminusicon="minusicon<?= $quest['quest_id'] ?><?= $step['npc_id'] ?><?= $step['step_number'] ?>" data-npcarrowup="npcarrowup<?= $quest['quest_id'] ?><?= $step['npc_id'] ?><?= $step['step_number'] ?>" data-npcarrowdown="npcarrowdown<?= $quest['quest_id'] ?><?= $step['npc_id'] ?><?= $step['step_number'] ?>" data-stepid="<?= $step['step_id'] ?>" data-dialogueicon="dialogueicon<?= $step['step_id'] ?>">

            <img src="./public/uploads/NPC_img/<?= $step['npc_image'] ?>" alt="<?= $step['npc_name'] ?>'s photo">
            <div class="npc-infos under-text-1">
                <p>Order: <?= $step['step_number'] ?></p>
                <p>Name: <?= $step['npc_name'] ?></p>
                <p>Id: <?= $step['npc_id'] ?></p>
            </div>

            <div class="tools">
                <div class="edit-pen none" id="dialogueicon<?= $step['step_id'] ?>">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
                    </svg>
                </div>
                <div class="change-npc-order">
                    <div class="edit-pen" id="npcarrowup<?= $quest['quest_id'] ?><?= $step['npc_id'] ?><?= $step['step_number'] ?>">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 15.75l7.5-7.5 7.5 7.5" />
                        </svg>
                    </div>
                    <div class="edit-pen" id="npcarrowdown<?= $quest['quest_id'] ?><?= $step['npc_id'] ?><?= $step['step_number'] ?>">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                        </svg>
                    </div>
                </div>
                <div class="remove-npc-from-quest delete" id="minusicon<?= $quest['quest_id'] ?><?= $step['npc_id'] ?><?= $step['step_number'] ?>">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                </div>
            </div>

        </div>
    <?php endforeach; ?>
<?php endif; ?>