<div class="form-type-1">
    <h2>Create Account</h2>
    <?php require "views/_errors.phtml" ?>
    <form action="index.php?page=create-account" method="POST">
        <div>
            <label for="email">User's email:</label>
            <input type="email" id="eamil" name="email" value="<?php echo isset($_POST['email']) ? $_POST['email'] : ''; ?>">
        </div>
        <div>
            <input type="submit" value="Create account">
        </div>
    </form>
</div>