<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin_NPC</title>
    <link rel="stylesheet" href="public/style/style.css">
    <script src="public/js/<?= $JavaScript ?>" type="module"></script>
</head>

<body>
    <header>
        <h1>Admin_npc</h1>
        <nav>
            <a href="index.php?page=quest">Manage quests</a>
            <a href="index.php?page=create-quest">Add Quest</a>
            <a href="index.php?page=NPC">Manage NPCs</a>
            <a href="index.php?page=create-NPC">Add NPC</a>
        </nav>
    </header>
    <main>
        <?php require_once $template ?>
    </main>
    <footer></footer>
</body>

</html>