<?php require "views/_errors.phtml"; ?>
<?php if (isset($NPCArray)) : ?>

    <?php foreach ($NPCArray as $NPC) : ?>
        <div class="npc-card">
            <div class="tools">
                <div class="edit-NPC-pen edit-pen">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
                    </svg>
                </div>
                <a class="delete-npc delete" href="index.php?page=delete-NPC&id=<?= $NPC['id'] ?>&filename=<?= $NPC['image'] ?>">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                    </svg>
                </a>
            </div>


            <img src="./public/uploads/NPC_img/<?= $NPC['image'] ?>" alt="Photo of <?= htmlspecialchars($NPC['name']) ?>">
            <div class="npc-infos">
                <h3><?= htmlspecialchars($NPC['name']) ?></h3>
                <p><span class="under-text-1">Id:</span> <?= $NPC['id'] ?></p>
            </div>

            <div class="none edit-NPC-form close-edit">
                <div class="close-edit-NPC tools">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="black" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </div>

                <form action="index.php?page=update-NPC" method="post" enctype="multipart/form-data">
                    <input type="hidden" value="<?= $NPC['id'] ?>" name="update-NPC-id">
                    <input type="hidden" value="<?= $NPC['image'] ?>" name="old-NPC-photo">
                    <div>
                        <label for="update-NPC-name">Update <?= htmlspecialchars($NPC['name']) ?>'s name:</label>
                        <input type="text" name="update-NPC-name" value="<?= htmlspecialchars($NPC['name']) ?>">
                    </div>
                    <div>
                        <label for="update-NPC-image">Update <?= htmlspecialchars($NPC['name']) ?>
                            's photo:
                        </label>
                        <input type="file" name="update-NPC-image" accept="image/png, image/jpeg">
                    </div>
                    <input type="submit" value="Validate">
                </form>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>